bitbreakers/bit-breaker-repository

Milestone 2/Class_Project_Definition_201920.md
=> Plz merge once more

Milestone 3/ThrowawayProject/ThrowawayProject/App_Data/down.sql, Milestone 3/ThrowawayProject/ThrowawayProject/App_Data/up.sql, Milestone 3/ThrowawayProject/ThrowawayProject/ThrowawayProject.csproj
For me I had to name my database aspnet-ThrowawayProject-20200123105315
So make sure to do that
=> Added up/down script and verified working account stuff

Milestone 3/ThrowawayProject/ThrowawayProject/Controllers/ProfileController.cs, Milestone 3/ThrowawayProject/ThrowawayProject/ThrowawayProject.csproj, Milestone 3/ThrowawayProject/ThrowawayProject/Views/Profile/settings.cshtml, Milestone 3/ThrowawayProject/ThrowawayProject/Views/Shared/_Layout.cshtml
This is adding a profile settings page to the main project. I have merged my dev branch into my profile-settings feature branch and received no merge conflicts. It should be good to go.
=> Profile settings

Milestone 3/ThrowawayProject/ThrowawayProject/Controllers/AccountController.cs, Milestone 3/ThrowawayProject/ThrowawayProject/Models/CaptchaResponse.cs, Milestone 3/ThrowawayProject/ThrowawayProject/Models/IdentityModels.cs, Milestone 3/ThrowawayProject/ThrowawayProject/ThrowawayProject.csproj, Milestone 3/ThrowawayProject/ThrowawayProject/Views/Account/Register.cshtml, Milestone 3/ThrowawayProject/ThrowawayProject/Views/Shared/_Layout.cshtml, Milestone 3/ThrowawayProject/ThrowawayProject/Web.config
Added captcha feature to feature branch. It is required to be used when creating a new account. I merged from my dev so there should be no merge conflicts.
=> added google api captcha

Milestone 3/ThrowawayProject/ThrowawayProject/App_Data/Athletedown.sql, Milestone 3/ThrowawayProject/ThrowawayProject/App_Data/Athleteup.sql, Milestone 3/ThrowawayProject/ThrowawayProject/Controllers/HomeController.cs, Milestone 3/ThrowawayProject/ThrowawayProject/Controllers/RaceResultsController.cs, Milestone 3/ThrowawayProject/ThrowawayProject/DAL/AthleteContext.cs, Milestone 3/ThrowawayProject/ThrowawayProject/Models/Athlete.cs, Milestone 3/ThrowawayProject/ThrowawayProject/Models/Coach.cs, Milestone 3/ThrowawayProject/ThrowawayProject/Models/Meet.cs, Milestone 3/ThrowawayProject/ThrowawayProject/Models/RaceResult.cs, Milestone 3/ThrowawayProject/ThrowawayProject/Models/Team.cs, Milestone 3/ThrowawayProject/ThrowawayProject/ThrowawayProject.csproj, Milestone 3/ThrowawayProject/ThrowawayProject/Views/Home/IndexList.cshtml, Milestone 3/ThrowawayProject/ThrowawayProject/Views/RaceResults/Index.cshtml, Milestone 3/ThrowawayProject/ThrowawayProject/Views/Shared/_Layout.cshtml, Milestone 3/ThrowawayProject/ThrowawayProject/Web.config
=> plox add feature to website plox

SimplySeniors/SimplySeniors/SimplySeniors/App_Data/MainDown.sql, SimplySeniors/SimplySeniors/SimplySeniors/App_Data/MainUp.sql, SimplySeniors/SimplySeniors/SimplySeniors/Controllers/ProfilesController.cs, SimplySeniors/SimplySeniors/SimplySeniors/DAL/ProfileContext.cs, SimplySeniors/SimplySeniors/SimplySeniors/Models/Profile.cs, SimplySeniors/SimplySeniors/SimplySeniors/SimplySeniors.csproj, SimplySeniors/SimplySeniors/SimplySeniors/Views/Profiles/Create.cshtml, SimplySeniors/SimplySeniors/SimplySeniors/Views/Profiles/Delete.cshtml, SimplySeniors/SimplySeniors/SimplySeniors/Views/Profiles/Details.cshtml, SimplySeniors/SimplySeniors/SimplySeniors/Views/Profiles/Edit.cshtml, SimplySeniors/SimplySeniors/SimplySeniors/Views/Profiles/Index.cshtml, SimplySeniors/SimplySeniors/SimplySeniors/Web.config, toolList.md
no upset if not work ok i merge reel gud
=> added profile upscript with seed data and CRUD functionality

SimplySeniors/SimplySeniors/SimplySeniors/Controllers/AccountController.cs, SimplySeniors/SimplySeniors/SimplySeniors/Models/CaptchaResponse.cs, SimplySeniors/SimplySeniors/SimplySeniors/SimplySeniors.csproj, SimplySeniors/SimplySeniors/SimplySeniors/Views/Account/Register.cshtml, SimplySeniors/SimplySeniors/SimplySeniors/Views/Shared/_Layout.cshtml, SimplySeniors/SimplySeniors/SimplySeniors/Web.config
Added public CaptchaResponse in AccountController that deserializes json provided by the api. Added public and private keys in web.config ,created a model that determines if the captcha was used by the user successfully and added the captcha in the form of HTML to the registration view.
=> Captcha feature (Should work)

SimplySeniors/SimplySeniors/SimplySeniors/Web.config
Unencrypted appSettings in web.config. Work now I hope.
=> Unencrypted appSettings

SimplySeniors/SimplySeniors/SimplySeniors/Controllers/AccountController.cs, SimplySeniors/SimplySeniors/SimplySeniors/SimplySeniors.csproj, SimplySeniors/SimplySeniors/SimplySeniors/Views/Account/Confirm.cshtml
Merged and working correctly, should be good to go.
=> RegistrationEmail-Feature 

SimplySeniors/SimplySeniors/SimplySeniors/App_Data/MainUp.sql, SimplySeniors/SimplySeniors/SimplySeniors/Controllers/ProfilesController.cs, SimplySeniors/SimplySeniors/SimplySeniors/Models/Profile.cs, SimplySeniors/SimplySeniors/SimplySeniors/Views/Profiles/Create.cshtml, SimplySeniors/SimplySeniors/SimplySeniors/Views/Profiles/Delete.cshtml, SimplySeniors/SimplySeniors/SimplySeniors/Views/Profiles/Details.cshtml, SimplySeniors/SimplySeniors/SimplySeniors/Views/Profiles/Edit.cshtml, SimplySeniors/SimplySeniors/SimplySeniors/Views/Profiles/Index.cshtml, SimplySeniors/SimplySeniors/SimplySeniors/Views/Shared/_Layout.cshtml
dont look at the details layout, you will feel sick
=> Added new fields to upscript, changed layout of details page to look 'better'

SimplySeniors/SimplySeniors/SimplySeniors/Controllers/AccountController.cs, SimplySeniors/SimplySeniors/SimplySeniors/Views/Account/Login.cshtml
Email is sent to confirmed accounts otherwise it doesn't tell the user if the account doesn't exist in the site. Merged dev into feature branch and fixed merge conflicts.
=> Passwords can now be reset on the login section of the project. 

SimplySeniors/SimplySeniors/SimplySeniors/Controllers/ProfilesController.cs
Updated so search matches first and/or last names, as opposed to just last names.
=> Fixed name search

SimplySeniors/SimplySeniors/SimplySeniors/App_Data/MainUp.sql, SimplySeniors/SimplySeniors/SimplySeniors/Controllers/ProfilesController.cs, SimplySeniors/SimplySeniors/SimplySeniors/Models/ViewModel/PDViewModel.cs, SimplySeniors/SimplySeniors/SimplySeniors/SimplySeniors.csproj, SimplySeniors/SimplySeniors/SimplySeniors/Views/Profiles/Details.cshtml
Yeah i checked out a commit while working on this, dont @ me bro
=> added viewmodel to show hobbies on profile page

SimplySeniors/SimplySeniors/SimplySeniors/App_Data/MainDown.sql, SimplySeniors/SimplySeniors/SimplySeniors/App_Data/MainUp.sql, SimplySeniors/SimplySeniors/SimplySeniors/Controllers/AccountController.cs, SimplySeniors/SimplySeniors/SimplySeniors/Controllers/ProfilesController.cs, SimplySeniors/SimplySeniors/SimplySeniors/DAL/ProfileContext.cs, SimplySeniors/SimplySeniors/SimplySeniors/Models/IdentityModels.cs, SimplySeniors/SimplySeniors/SimplySeniors/Models/Profile.cs, SimplySeniors/SimplySeniors/SimplySeniors/SimplySeniors.csproj, SimplySeniors/SimplySeniors/SimplySeniors/Views/Profiles/Create.cshtml, SimplySeniors/SimplySeniors/SimplySeniors/Views/Profiles/Details.cshtml, SimplySeniors/SimplySeniors/SimplySeniors/Views/Profiles/Edit.cshtml, SimplySeniors/SimplySeniors/SimplySeniors/Views/Profiles/Index.cshtml
This is an early pull request so user stories from another teammate can be completed.
=> Profile feature

SimplySeniors/SimplySeniors/SimplySeniors/App_Data/MainDown.sql, SimplySeniors/SimplySeniors/SimplySeniors/App_Data/MainUp.sql, SimplySeniors/SimplySeniors/SimplySeniors/Controllers/PostsController.cs, SimplySeniors/SimplySeniors/SimplySeniors/Controllers/UserHomePageController.cs, SimplySeniors/SimplySeniors/SimplySeniors/DAL/EventContext.cs, SimplySeniors/SimplySeniors/SimplySeniors/DAL/HobbiesContext.cs, SimplySeniors/SimplySeniors/SimplySeniors/DAL/PostContext.cs, SimplySeniors/SimplySeniors/SimplySeniors/DAL/ProfileContext.cs, SimplySeniors/SimplySeniors/SimplySeniors/Models/IdentityModels.cs, SimplySeniors/SimplySeniors/SimplySeniors/Models/Profile.cs, SimplySeniors/SimplySeniors/SimplySeniors/Models/ViewModel/UserHomeViewModel.cs, SimplySeniors/SimplySeniors/SimplySeniors/SimplySeniors.csproj, SimplySeniors/SimplySeniors/SimplySeniors/Views/UserHomePage/HomePage.cshtml
dont @ me bro its just a prank bro chill youre on camera haha
Make sure to like comment and subscribe
=> Post integration feature

SimplySeniors/SimplySeniors/SimplySeniors/Views/Account/ExternalLoginConfirmation.cshtml, SimplySeniors/SimplySeniors/SimplySeniors/Views/Account/ForgotPassword.cshtml, SimplySeniors/SimplySeniors/SimplySeniors/Views/Account/ResetPassword.cshtml, SimplySeniors/SimplySeniors/SimplySeniors/Views/Account/SendCode.cshtml, SimplySeniors/SimplySeniors/SimplySeniors/Views/Account/VerifyCode.cshtml, SimplySeniors/SimplySeniors/SimplySeniors/Views/Account/_ExternalLoginsListPartial.cshtml, SimplySeniors/SimplySeniors/SimplySeniors/Views/Events/Create.cshtml, SimplySeniors/SimplySeniors/SimplySeniors/Views/Events/Delete.cshtml, SimplySeniors/SimplySeniors/SimplySeniors/Views/Events/Edit.cshtml, SimplySeniors/SimplySeniors/SimplySeniors/Views/Hobbies/Create.cshtml, SimplySeniors/SimplySeniors/SimplySeniors/Views/Hobbies/Edit.cshtml, SimplySeniors/SimplySeniors/SimplySeniors/Views/Hobbies/Index.cshtml, SimplySeniors/SimplySeniors/SimplySeniors/Views/Manage/AddPhoneNumber.cshtml, SimplySeniors/SimplySeniors/SimplySeniors/Views/Manage/ChangePassword.cshtml, SimplySeniors/SimplySeniors/SimplySeniors/Views/Manage/ManageLogins.cshtml, SimplySeniors/SimplySeniors/SimplySeniors/Views/Manage/SetPassword.cshtml, SimplySeniors/SimplySeniors/SimplySeniors/Views/Manage/VerifyPhoneNumber.cshtml, SimplySeniors/SimplySeniors/SimplySeniors/Views/Posts/Create.cshtml, SimplySeniors/SimplySeniors/SimplySeniors/Views/Posts/Delete.cshtml, SimplySeniors/SimplySeniors/SimplySeniors/Views/Posts/Details.cshtml, SimplySeniors/SimplySeniors/SimplySeniors/Views/Posts/Edit.cshtml, SimplySeniors/SimplySeniors/SimplySeniors/Views/Profiles/Create.cshtml, SimplySeniors/SimplySeniors/SimplySeniors/Views/Profiles/Delete.cshtml, SimplySeniors/SimplySeniors/SimplySeniors/Views/Profiles/Details.cshtml, SimplySeniors/SimplySeniors/SimplySeniors/Views/Profiles/Edit.cshtml
Went through and tried to ensure all clickable icons appear as buttons. Also updated the ActionLinks to match styling from Events pages and removed some redundant CRUD from some Identity views.
=> Replaced all missing buttons and modified ActionLinks

SimplySeniors/SimplySeniors/SimplySeniors/App_Data/MainDown.sql, SimplySeniors/SimplySeniors/SimplySeniors/DAL/EventContext.cs, SimplySeniors/SimplySeniors/SimplySeniors/DAL/HobbiesContext.cs, SimplySeniors/SimplySeniors/SimplySeniors/DAL/PostContext.cs, SimplySeniors/SimplySeniors/SimplySeniors/DAL/ProfileContext.cs, SimplySeniors/SimplySeniors/SimplySeniors/Models/IdentityModels.cs, SimplySeniors/SimplySeniors/SimplySeniors/PhotoDownloadForm.aspx.cs, SimplySeniors/SimplySeniors/SimplySeniors/Views/Profiles/Details.cshtml
Covid makes me not want to do homework anymore [PRANKED][GONE WRONG][GIVEAWAY]
=> Changed details view to match the home page better

SimplySeniors/SimplySeniors/SimplySeniors/Controllers/ProfilesController.cs
=> fixed profile creation bug

SimplySeniors/SimplySeniors/SimplySeniors/Content/Site.css, SimplySeniors/SimplySeniors/SimplySeniors/DAL/EventContext.cs, SimplySeniors/SimplySeniors/SimplySeniors/DAL/FollowContext.cs, SimplySeniors/SimplySeniors/SimplySeniors/DAL/HobbiesContext.cs, SimplySeniors/SimplySeniors/SimplySeniors/DAL/PostContext.cs, SimplySeniors/SimplySeniors/SimplySeniors/DAL/ProfileContext.cs, SimplySeniors/SimplySeniors/SimplySeniors/Models/IdentityModels.cs, SimplySeniors/SimplySeniors/SimplySeniors/PhotoDownloadForm.aspx.cs, SimplySeniors/SimplySeniors/SimplySeniors/PhotoUploadForm.aspx.cs, SimplySeniors/SimplySeniors/SimplySeniors/Views/FollowLists/Create.cshtml, SimplySeniors/SimplySeniors/SimplySeniors/Views/FollowLists/Delete.cshtml, SimplySeniors/SimplySeniors/SimplySeniors/Views/FollowLists/Details.cshtml, SimplySeniors/SimplySeniors/SimplySeniors/Views/FollowLists/Edit.cshtml, SimplySeniors/SimplySeniors/SimplySeniors/Views/HobbyBridges/Create.cshtml, SimplySeniors/SimplySeniors/SimplySeniors/Views/HobbyBridges/Delete.cshtml, SimplySeniors/SimplySeniors/SimplySeniors/Views/HobbyBridges/Edit.cshtml, SimplySeniors/SimplySeniors/SimplySeniors/Views/Home/Services.cshtml
Added reverse mortgage card to services page. Edited some non related elements, more info in pivotal if needed.
=> Federal funding services feature

SimplySeniors/SimplySeniors/SimplySeniors/Models/WeatherAPI.cs, SimplySeniors/SimplySeniors/SimplySeniors/PhotoDownloadForm.aspx.cs, SimplySeniors/SimplySeniors/SimplySeniors/PhotoUploadForm.aspx.cs, SimplySeniors/SimplySeniors/SimplySeniors/Views/Profiles/Details.cshtml, SimplySeniors/SimplySeniors/SimplySeniors/weather.aspx
Added city and state dynamically to weather widget on homepage. Hid the search bar and button, but left in case we use the widget elsewhere.
=> Dynamic weather widget feature

SimplySeniors/SimplySeniors/SimplySeniors/Controllers/ProfilesController.cs, SimplySeniors/SimplySeniors/SimplySeniors/SimplySeniors.csproj, SimplySeniors/SimplySeniors/SimplySeniors/Views/Profiles/MyProfile.cshtml, SimplySeniors/SimplySeniors/SimplySeniors/Views/Shared/_Layout.cshtml
I had to create a new actionresult in profiles called "Myprofile" since details requires an id and having two details throws an asynchronous error in mvc.
=> added profile to layout index

SimplySeniors/SimplySeniors/SimplySeniors/Controllers/UserHomePageController.cs
Users should now have a dynamic map depending on what city and state they put in.
=> created dynamic map 

SimplySeniors/SimplySeniors/SimplySeniors/Controllers/UserHomePageController.cs, SimplySeniors/SimplySeniors/SimplySeniors/Views/Profiles/Create.cshtml
Also Shamelessly stole the css from the profile edit view.
=> Map bug fix

SimplySeniors/SimplySeniors/SimplySeniors/SimplySeniors.csproj
=> Post redirect

SimplySeniors/SimplySeniors/SimplySeniors/PhotoUploadForm.aspx.cs, SimplySeniors/SimplySeniors/SimplySeniors/Views/Profiles/Details.cshtml
Also commented back in the images feature so we can upload images for product owner display on Tuesday.
=> pushing up quick bug fix in Image Id to default to 1 to resolve errors with photoUploadForm. 

SimplySeniors/SimplySeniors/SimplySeniors/Views/UserHomePage/NewsFeed.cshtml
=> Added link to article

SimplySeniors/SimplySeniors/SimplySeniors/Content/Site.css, SimplySeniors/SimplySeniors/SimplySeniors/Views/Events/SearchEvents.cshtml, SimplySeniors/SimplySeniors/SimplySeniors/Views/Profiles/Index.cshtml
Modified the search features for events and profiles. Modified the way the results are shown and the styling, also added images to all of the search results.
=> Re configure search feature

SimplySeniors/SimplySeniors/SimplySeniors/Views/Profiles/MyProfile.cshtml
RE-did the About me section on profile. To make biography readable, ended up re-styling the whole container to match the look.
=> Move bio profile page feature

SimplySeniors/SimplySeniors/SimplySeniors/PhotoDownloadForm.aspx, SimplySeniors/SimplySeniors/SimplySeniors/PhotoDownloadForm.aspx.cs, SimplySeniors/SimplySeniors/SimplySeniors/Views/Profiles/Create.cshtml, SimplySeniors/SimplySeniors/SimplySeniors/Views/Profiles/Index.cshtml
Created logic for a default no image photo instead of server errors when photos are not uploaded, per user story from icebox.
=> Place holder photo feature

SimplySeniors/SimplySeniors/SimplySeniors/Controllers/FollowListsController.cs, SimplySeniors/SimplySeniors/SimplySeniors/Views/Profiles/Details.cshtml
Make sure to smash that like button and remember to subscribe
Follow my twitter : "elonmusk"
=> Finished new follow user feature

SimplySeniors/SimplySeniors/SimplySeniors/Controllers/FollowListsController.cs, SimplySeniors/SimplySeniors/SimplySeniors/Controllers/ProfilesController.cs, SimplySeniors/SimplySeniors/SimplySeniors/Models/ViewModel/FollowerInheritanceModel.cs, SimplySeniors/SimplySeniors/SimplySeniors/Models/ViewModel/FollowerSearch.cs, SimplySeniors/SimplySeniors/SimplySeniors/Scripts/main.js, SimplySeniors/SimplySeniors/SimplySeniors/SimplySeniors.csproj, SimplySeniors/SimplySeniors/SimplySeniors/Views/FollowLists/AjaxCreate.cshtml, SimplySeniors/SimplySeniors/SimplySeniors/Views/Profiles/search.cshtml, SimplySeniors/SimplySeniors/SimplySeniors/Views/UserHomePage/HomePage.cshtml
Search feature now works, made sure existing following feature works, ajax works, and names are sorted properly.  Recommendation goes in this order (State,Hobby) -> (State) -> (Everyone else).
=> Search feature
